### ISSUE TITLE
NPE if bad network interface chosen

### ISSUE THREAD

**Issue by yschimke** [yschimke/oksocial#214]
10:44 $ fbapi --networkInterface en0 /me
unknown error
java.lang.NullPointerException
	at com.baulsupp.oksocial.network.InterfaceSocketFactory.byName(InterfaceSocketFactory.java:51)
	at com.baulsupp.oksocial.Main.createClientBuilder(Main.java:576)
	at com.baulsupp.oksocial.Main.initialise(Main.java:411)
	at com.baulsupp.oksocial.Main.run(Main.java:263)
	at com.baulsupp.oksocial.Main.main(Main.java:101)

**Comment by yschimke** [comment]
https://github.com/yschimke/oksocial/pull/216
